export const phoneCode = [
  {code: "+7", country: "Россия", flag: "flag-ru"},
  {code: "+355", country: "Албания", flag: "flag-al"},
  {code: "+213", country: "Алжир", flag: "flag-dz"},
  {code: "+244", country: "Ангола", flag: "flag-ao"},
  {code: "+376", country: "Андорра", flag: "flag-ad"},
  {code: "+374", country: "Армения", flag: "flag-am"},
  {code: "+994", country: "Азербайджан", flag: "flag-az"},
  {code: "+880", country: "Бангладеш", flag: "flag-bd"},
  {code: "+375", country: "Беларусь", flag: "flag-by"},
  {code: "+995", country: "Грузия", flag: "flag-ge"},
  {code: "+7",  country: "Казахстан", flag: "flag-kz"},
  {code: "+996", country: "Кыргызстан", flag: "flag-kg"},
  {code: "+371", country: "Латвия", flag: "flag-lv"},
  {code: "+370", country: "Литва", flag: "flag-lt"},
  {code: "+373", country: "Молдова", flag: "flag-md"},
  {code: "+998", country: "Узбекистан", flag: "flag-uz"},
  {code: "+380", country: "Украина", flag: "flag-ua"},
  {code: "+372", country: "Эстония", flag: "flag-ee"}, 
  
]